apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-service
  template:
    metadata:
      labels:
        app: hotel-service
    spec:
      containers:
        - name: hotel-service
          image: <DOCKER_USER>/hotel-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8085
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://service-registry:8761/eureka/
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-db:5432/microservices
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-service
  namespace: microservices
spec:
  selector:
    app: hotel-service
  ports:
    - port: 8082
  type: ClusterIP
