apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
        - name: service-registry
          image: <DOCKER_USER>/service-registry:latest
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8085
---
apiVersion: v1
kind: Service
metadata:
  name: service-registry
  namespace: microservices
spec:
  selector:
    app: service-registry
  ports:
    - port: 8761
  type: ClusterIP
