server:
  port: 8082

spring:
  application:
    name: HOTEL-SERVICE
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://config-server:8085
      fail-fast: true
      retry:
        initial-interval: 2000
        multiplier: 1.5
        max-interval: 10000
        max-attempts: 10

  datasource:
    url: jdbc:postgresql://postgres-db:5432/microservices
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
