server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:3308/microservices
    username: postgres
    password: root
#    driver-class-name: com.postgresql.cj.jdbc.Driver
#  driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect

  application:
    name: HOTEL-SERVICE
eureka:
  instance:
    #    hostname: localhost
    appname: HOTEL-SERVICE
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/